<?php

function papirby_register_acf_field_groups() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6641d144ba882',
	'title' => 'Afdelinger',
	'fields' => array(
		array(
			'key' => 'field_6641d14555486',
			'label' => 'Afdelings billed',
			'name' => 'afdelings_billed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6641d18855487',
			'label' => 'Afdelings billed kredit',
			'name' => 'afdelings_billed_kredit',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6641d19b55488',
			'label' => 'Adresse',
			'name' => 'afdelings_adresse',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6641dba62b282',
			'label' => 'Kontakt',
			'name' => 'afdelings_kontakt',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/afdeling.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_661837eaae44c',
	'title' => 'Enheder',
	'fields' => array(
		array(
			'key' => 'field_661837ebea15e',
			'label' => 'Aldersgruppe',
			'name' => 'aldersgruppe',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66183824ea15f',
			'label' => 'Mødetidspunkt',
			'name' => 'modetidspunkt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6618387706b30',
			'label' => 'Enheds billed',
			'name' => 'enheds_billed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_661839273eb69',
			'label' => 'Billed kredit',
			'name' => 'enheds_billed_kredit',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66425d2ee17c7',
			'label' => 'Billed kredit (Kopier)',
			'name' => 'enheds_billed_kredit_Kopier',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66183839ea160',
			'label' => 'Enhedsleder',
			'name' => 'enhedsleder',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_66425d37e17c8',
			'label' => 'Enhedsleder billed',
			'name' => 'enhedsleder_billed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6641ec81f72a5',
			'label' => 'Program',
			'name' => 'enheds_program',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'uploadedTo',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6641eca2f72a6',
			'label' => 'Programmet udløber',
			'name' => 'enheds_programmet_udlober',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Angiv hvornår programmet udløber. Så bliver programmet skjult efter den dato. Hvis den efterlades tom, bliver programmet altid vist.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'j. F, Y',
			'return_format' => 'd-m-Y',
			'first_day' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'enheder',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_661835bc5e2a4',
	'title' => 'Forside',
	'fields' => array(
		array(
			'key' => 'field_661835bd65f7e',
			'label' => 'Herospot titel',
			'name' => 'herospot_title',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_6618363045b11',
			'label' => 'Herospot tekst',
			'name' => 'herospot_tekst',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6645f1a81a84a',
			'label' => 'Herospot billed',
			'name' => 'herospot_billed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6645f299fef5e',
			'label' => 'Herospot billed kredit',
			'name' => 'herospot_billed_kredit',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6645f1b41a84b',
			'label' => 'Map tekst',
			'name' => 'map_tekst',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/forside.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66280745cb441',
	'title' => 'Nyheder',
	'fields' => array(
		array(
			'key' => 'field_662807464883d',
			'label' => 'Forside teaser',
			'name' => 'forside_teaser',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_begivenheder_fields',
	'title' => 'Begivenhedsdetaljer',
	'fields' => array(
		array(
			'key' => 'field_begivenhed_start_dato',
			'label' => 'Start dato og tidspunkt',
			'name' => 'start_dato',
			'type' => 'date_time_picker',
			'instructions' => 'Dato og starttidspunkt for begivenheden (bruges til kronologisk sortering)',
			'required' => 1,
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
		),
		array(
			'key' => 'field_begivenhed_slut_dato',
			'label' => 'Slut dato og tidspunkt',
			'name' => 'slut_dato',
			'type' => 'date_time_picker',
			'instructions' => 'Valgfrit for flerdages arrangementer eller specifik slut-tid',
			'required' => 0,
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
		),
		array(
			'key' => 'field_begivenhed_tidspunkt_tekst',
			'label' => 'Tidspunkt (tekst)',
			'name' => 'tidspunkt_tekst',
			'type' => 'text',
			'instructions' => 'f.eks. "Kl. 18:30 - 20:00" eller "Lørdag kl. 10.00 til søndag kl. 14.00"',
			'required' => 0,
		),
		array(
			'key' => 'field_begivenhed_location_sted',
			'label' => 'Sted / Mødested',
			'name' => 'location_sted',
			'type' => 'text',
			'instructions' => 'f.eks. "Spejderhytten, Silkeborg" eller "Kongehøjlejren"',
			'required' => 0,
		),
		array(
			'key' => 'field_begivenhed_pris',
			'label' => 'Pris',
			'name' => 'pris',
			'type' => 'text',
			'instructions' => 'f.eks. "50 kr." eller "Gratis"',
			'required' => 0,
		),
		array(
			'key' => 'field_begivenhed_tilmeldingsfrist',
			'label' => 'Tilmeldingsfrist',
			'name' => 'tilmeldingsfrist',
			'type' => 'date_picker',
			'instructions' => 'Sidste frist for tilmelding',
			'required' => 0,
			'display_format' => 'd/m/Y',
			'return_format' => 'Y-m-d',
			'first_day' => 1,
		),
		array(
			'key' => 'field_begivenhed_tilmeldings_link',
			'label' => 'Tilmeldingslink',
			'name' => 'tilmeldings_link',
			'type' => 'url',
			'instructions' => 'Direkte link til tilmelding på Medlemsservice eller eksternt skjema',
			'required' => 0,
		),
		array(
			'key' => 'field_begivenhed_kontaktperson',
			'label' => 'Kontaktperson',
			'name' => 'kontaktperson',
			'type' => 'wysiwyg',
			'instructions' => 'Navn, e-mail eller telefonnummer på den ansvarlige leder',
			'required' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'begivenheder',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'active' => true,
	'show_in_rest' => 1,
) );
}

if ( function_exists( 'acf_add_local_field_group' ) ) {
    papirby_register_acf_field_groups();
} else {
    add_action( 'acf/init', 'papirby_register_acf_field_groups' );
}

